'use client'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar'
import GlobalStyles from './styles/GlobalStyles'
import Footer from './components/footer'
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Agendamento Divam',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalStyles />
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </body>
    </html>
  )
}
